# Generated by Django 3.1 on 2020-08-29 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0003_post_title_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Title_tag',
        ),
    ]
